import React from "react";
import Document, { Html, Head, Main, NextScript } from "next/document";
import { ServerStyleSheet } from "styled-components";

class MyDocument extends Document {
	render() {
		const sheet = new ServerStyleSheet();
		const main = sheet.collectStyles(<Main />);
		const styleTags = sheet.getStyleElement();
		return (
			<Html>
				<Head>
					<title>App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
					<link rel="stylesheet" href="/static/css/style.css" />
					<link
						async
						rel="stylesheet"
						href="https://cdn.jsdelivr.net/npm/semantic-ui@2/dist/semantic.min.css"
						href="/static/vendor/node_modules/owl.carousel/dist/assets/owl.carousel.min.css"
					/>
					<script src="https://www.google.com/recaptcha/api.js?hl=th"></script>
					<link
						rel="stylesheet"
						href="/static/vendor/node_modules/bootstrap/dist/css/bootstrap.min.css"
					/>
					<link
						rel="stylesheet"
						href="/static/vendor/node_modules/owl.carousel/dist/assets/owl.carousel.min.css"
					/>
					<link
						rel="stylesheet"
						href="/static/vendor/node_modules/owl.carousel/dist/assets/owl.theme.default.min.css"
					/>
					<script
						type="text/javascript"
						src="/static/vendor/node_modules/jquery/dist/jquery.min.js"
					/>
					<script
						type="text/javascript"
						src="/static/vendor/node_modules/bootstrap/dist/js/bootstrap.min.js"
					/>
					<script
						type="text/javascript"
						src="/static/vendor/node_modules/owl.carousel/dist/owl.carousel.min.js"
					/>
					<script
						type="text/javascript"
						src="/static/vendor/node_modules/popper.js/dist/umd/popper.min.js"
					/>
					<script src="https://cdn.jsdelivr.net/npm/semantic-ui-react/dist/umd/semantic-ui-react.min.js"></script>
					{styleTags}
				</Head>
				<body>
					{main}
					<NextScript />
				</body>
			</Html>
		);
	}
}

export default MyDocument;
